export const COVERAGE_LOCATIONS = [
  {
    zone: 'Callao',
    cities: [
      'Bellavista',
      'Callao',
      'Carmen de la legua',
      'La perla',
      'La punta',
      'Ventanilla',
      'Mi Perú',
    ],
  },
  {
    zone: 'Lima Centro',
    cities: ['Breña', 'La Victoria', 'Lima (Cercado)', 'Rimac', 'San Luis'],
  },
  {
    zone: 'Lima Moderna',
    cities: [
      'Barranco',
      'Jesús María',
      'La Molina',
      'Lince',
      'Magdalena del Mar',
      'Miraflores',
      'Pueblo libre',
      'San Borja',
      'San Isidro',
      'San Miguel',
      'Santiago de Surco',
      'Surquillo',
    ],
  },
  {
    zone: 'Lima Norte',
    cities: [
      'Ancón',
      'Carabayllo',
      'Comas',
      'Independencia',
      'Los Olivos',
      'Puente Piedra',
      'San Martín de Porres',
      'Santa Rosa',
    ],
  },
  {
    zone: 'Lima Este',
    cities: [
      'Ate Vitarte',
      'Chaclacayo',
      'Cieneguilla',
      'El Agustino',
      'Lurigancho (Chosica)',
      'San Juan de Lurigancho',
      'Santa Anita',
    ],
  },
  {
    zone: 'Lima Sur',
    cities: [
      'Chorrillos',
      'Lurín',
      'Pachacamac',
      'Pucusana',
      'Punta Hermosa',
      'Punta Negra',
      'San Bartolo',
      'San Juan de Miraflores',
      'Santa María del Mar',
      'Villa el Salvador',
      'Villa María del Triunfo',
    ],
  },
]
